import Header from "./components/Header";
import "./globals.css";
// import { Inter } from "next/font/google";
// import { Mulish } from "next/font/google";
import Footer from "./components/Footer";

// const mulish = Mulish({
//   subsets: ["latin"],
//   display: "swap",

//   weight: ["400", "700", "900", "1000"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
